# Generated by Django 3.0.7 on 2021-08-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('name',), name='repository_type_unq'),
        ),
    ]
